dependencies:
  - name: mysql
    version: 8.0.29
    repository: "@bitnami"
    condition: mysql.enabled
  - name: postgresql
    version: 14.4.0
    repository: "@bitnami"
    condition: postgresql.enabled
  - name: rabbitmq
    version: 3.10.5
    repository: "@bitnami"
    condition: rabbitmq.enabled
  - name: redis
    version: 7.0.2
    repository: "@bitnami"
    condition: redis.enabled
