dependencies:
  - name: mysql
    version: 8.8.12
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: mysql.enabled
  - name: postgresql
    version: 10.13.4
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: postgresql.enabled
  - name: rabbitmq
    version: 8.24.2
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: rabbitmq.enabled
  - name: redis
    version: 15.5.4
    repository: "https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami"
    condition: redis.enabled
