# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "s3-bucket-tfstate-proj42-dev"
    dynamodb_table = "s3_state_lock_dev"
    encrypt        = true
    key            = "03-bastion/terraform.tfstate"
    region         = "us-east-2"
  }
}
